#Makefile at top of application tree
TOP = ../..
include $(TOP)/configure/CONFIG

DB += moduleversion.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
