#! /usr/bin/env python3
"""Entry point for the IOC shell."""

import argparse
import os
import logging
from pathlib import Path
import subprocess
import sys
import re
from typing import List

from iocsh_utils import verify_environment_and_return_require_version
from iocsh_utils import TemporaryStartupScript
from iocsh_utils import generate_banner
from iocsh_utils import fetch_debugger_args


def iocsh(
    file: Path,
    module: List[str],
    command: List[str],
    database: List[Path],
    no_init: bool,
    iocname: str,
    debugger: str,
    debugger_args: str,
    debug: bool,
):
    with TemporaryStartupScript(iocname) as tmp_startup_script:
        require_version = verify_environment_and_return_require_version()
        pvxs_dir = Path(os.environ["PVXS"])

        print(generate_banner())
        print(f"Starting e3 IOC shell version {require_version}")
        logging.debug(f"PID for iocsh {os.getpid()}")
        logging.debug(f"Script path is {Path(__file__).resolve()}")
        logging.debug(f"Executed from {Path.cwd()}")
        logging.debug(f"Temporary startup script at {tmp_startup_script.name}")

        if debug:
            tmp_startup_script.add_command("var requireDebug 1")

        for entry in module:
            tmp_startup_script.load_module(entry)

        if file:
            if not file.exists():
                logging.debug(f"File {file} does not exist. Exiting.")
                sys.exit(-1)
            tmp_startup_script.set_variable("E3_CMD_TOP", str(file.parent.resolve()))
            tmp_startup_script.load_snippet(file)

        for entry in command:
            tmp_startup_script.add_command(entry)

        for entry in database:
            tmp_startup_script.load_database(entry)

        if not no_init:
            # if file isn't passed we shouldn't try to read its' content
            if (
                not file
                or re.search(r"^\s*iocInit\b", file.read_text(), flags=re.MULTILINE)
                is None
            ):
                tmp_startup_script.add_command("iocInit")

        tmp_startup_script.save()

        cmd = [
            "softIocPVX",
            "-D",
            str(pvxs_dir / "dbd" / "softIocPVX.dbd"),
            tmp_startup_script.name,
        ]

        if debugger:
            cmd = [debugger] + fetch_debugger_args(debugger, debugger_args) + cmd

        logging.debug(f"Running command `{' '.join(cmd)}`")
        try:
            subprocess.run(cmd, check=True)
        except (KeyboardInterrupt, subprocess.CalledProcessError):
            sys.exit(-1)


def generate_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="IOC shell for e3",
        description="ESS EPICS environment (e3) wrapper for softIocPVA",
    )

    # How this is set up has a funny but sort of good side-effect:
    # if no environment is sourced the IOC shell will refuse to start in the first place
    # even if you try to execute something like `iocsh -h`
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version="%(prog)s version {_version}".format(
            _version=verify_environment_and_return_require_version()
        ),
        help="Print version and exit",
    )

    parser.add_argument(
        "file", type=Path, nargs="?", default=None, help="Path to startup script"
    )
    parser.add_argument(
        "-r",
        "--require",
        dest="module",
        action="append",
        default=list(),
        help="Load module(s), optionally with version using the syntax `module,version`",
    )
    parser.add_argument(
        "-c", "--command", action="append", default=list(), help="Execute command(s)"
    )
    parser.add_argument(
        "-d",
        "--database",
        action="append",
        default=list(),
        type=Path,
        help="Load database file(s) (`dbLoadRecords`)",
    )

    parser.add_argument(
        "--debugger",
        nargs="?",
        choices=["gdb", "lldb", "valgrind"],
        default=None,
        const="gdb",
        help='Run with selected debugger. To pass arguments, use --debuger-args "args"',
    )
    parser.add_argument(
        "--debugger-args", help="Arguments to pass to debugger", default=""
    )
    parser.add_argument(
        "--debug",
        action="store_true",
    )

    parser.add_argument("-i", "--no-init", action="store_true")

    parser.add_argument("--iocname", help="IOC name (generates fallback if not set)")

    return parser


if __name__ == "__main__":
    logging.basicConfig(format="%(levelname)s: %(message)s ", level=logging.DEBUG)
    parser = generate_parser()
    args = parser.parse_args()
    if args.debugger_args and not args.debugger:
        parser.error("Debugger arguments supplied, but no debugger specified.")

    iocsh(**vars(args))
