#! /usr/bin/env python3
"""Entry point for the IOC shell."""

import argparse
import os
import logging
from pathlib import Path
import subprocess
import sys
import re
from typing import List

from iocsh_utils import verify_environment_and_return_require_version
from iocsh_utils import TemporaryStartupScript
from iocsh_utils import generate_banner


def iocsh(
    file: Path,
    module: List[str],
    command: List[str],
    database: List[Path],
    cell_path: List[Path],
    no_init: bool,
    realtime: bool,
    gdb: bool,
    valgrind: str,
    debug: bool,
):
    with TemporaryStartupScript() as tmp_startup_script:
        require_version = verify_environment_and_return_require_version()
        epics_base_dir = Path(os.environ["EPICS_BASE"])

        print(generate_banner())
        print(f"Starting e3 IOC shell version {require_version}")
        try:
            iocname = os.environ["IOCNAME"]
        except KeyError:
            logging.warning("Environment variable IOCNAME is not set.")
        else:
            logging.info(f"IOCNAME is set to {iocname}")
        logging.debug(f"PID for iocsh {os.getpid()}")
        logging.debug(f"Script path is {Path(__file__).resolve()}")
        logging.debug(f"Executed from {Path.cwd()}")
        logging.debug(f"Temporary startup script at {tmp_startup_script.name}")

        if cell_path:
            cell_paths = ":".join(
                [
                    str(
                        p.resolve() / epics_base_dir.name / f"require-{require_version}"
                    )
                    for p in reversed(cell_path)
                ]
            )
            tmp_startup_script.set_variable(
                "EPICS_DRIVER_PATH", f"{cell_paths}:{os.environ['EPICS_DRIVER_PATH']}"
            )

        if debug:
            tmp_startup_script.add_command("var requireDebug 1")

        for entry in module:
            tmp_startup_script.load_module(entry)

        if file:
            tmp_startup_script.set_variable("E3_CMD_TOP", {str(file.parent)})
            tmp_startup_script.load_snippet(file)

        for entry in command:
            tmp_startup_script.add_command(entry)

        for entry in database:
            tmp_startup_script.load_database(entry)

        if not no_init:
            # if file isn't passed we shouldn't try to read its' content
            if not file or re.search(r"^\s*iocInit\b", file.read_text()) is None:
                tmp_startup_script.add_command("iocInit")

        tmp_startup_script.save()

        cmd = [
            str(epics_base_dir / "bin" / os.environ["EPICS_HOST_ARCH"] / "softIocPVA"),
            "-D",
            str(epics_base_dir / "dbd" / "softIocPVA.dbd"),
            tmp_startup_script.name,
        ]

        if gdb:
            cmd = ["gdb", "--args", cmd]
        elif valgrind:
            cmd = ["valgrind"] + valgrind.split(" ") + cmd
        elif realtime:
            os.environ["LD_BIND_NOW"] = 1
            cmd = "chrt --fifo 1".split(" ") + cmd

        logging.debug(f"Running command `{' '.join(cmd)}`")
        try:
            subprocess.run(cmd, check=True)
        except (KeyboardInterrupt, subprocess.CalledProcessError):
            sys.exit(-1)


def generate_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="IOC shell for e3",
        description="ESS EPICS environment (e3) wrapper for softIocPVA",
    )

    # How this is set up has a funny but sort of good side-effect:
    # if no environment is sourced the IOC shell will refuse to start in the first place
    # even if you try to execute something like `iocsh -h`
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version="%(prog)s version {_version}".format(
            _version=verify_environment_and_return_require_version()
        ),
        help="print version and exit",
    )

    parser.add_argument(
        "file", type=Path, nargs="?", default=None, help="path to startup script"
    )
    parser.add_argument(
        "-r",
        "--require",
        dest="module",
        action="append",
        default=list(),
        help="load module(s), optionally with version using the syntax `module,version`",
    )
    parser.add_argument(
        "-c", "--command", action="append", default=list(), help="execute command(s)"
    )
    parser.add_argument(
        "-d",
        "--database",
        action="append",
        default=list(),
        type=Path,
        help="load database file(s) (`dbLoadRecords`)",
    )
    parser.add_argument(
        "-l",
        "--cell-path",
        type=Path,
        action="append",
        default=list(),
        metavar="PATH",
        help="path(s) to cell(s)",
    )

    mutex_group_modifiers = parser.add_mutually_exclusive_group()
    mutex_group_modifiers.add_argument("-rt", "--realtime", action="store_true")
    mutex_group_modifiers.add_argument(
        "-dg",
        "--gdb",
        action="store_true",
        help="run with gdb",
    )
    mutex_group_modifiers.add_argument(
        "-dv",
        "--valgrind",
        nargs="?",
        const="--leak-check=full",
        metavar="ARGUMENT",
        help="run with valgrind",
    )
    mutex_group_modifiers.add_argument(
        "--debug",
        action="store_true",
    )

    parser.add_argument("-i", "--no-init", action="store_true")

    return parser


if __name__ == "__main__":
    logging.basicConfig(format="%(levelname)s: %(message)s ", level=logging.DEBUG)
    parser = generate_parser()
    args = parser.parse_args()
    iocsh(**vars(args))
