#Makefile at top of application tree
TOP = ../..
include $(TOP)/configure/CONFIG

SCRIPTS += iocsh
SCRIPTS += iocsh_complete.bash
SCRIPTS += iocsh_epics.supp
SCRIPTS += iocsh_utils.py
SCRIPTS += driver.makefile


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
