#Makefile at top of application tree
TOP = ../..
include $(TOP)/configure/CONFIG

SCRIPTS += iocsh
SCRIPTS += iocsh_complete.bash
SCRIPTS += iocsh_utils.py

SCRS += iocsh_epics.supp
SCRS += driver.makefile

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
